### ISSUE TITLE
Allow rendering Android Views

### ISSUE THREAD

**Issue by pavi2410** [zhanghai/BeeShell#3]
This feature is also available in the AJShA app. However, it is no longer updated nor it is available on the Play Store.

### Preview
<img src="https://user-images.githubusercontent.com/28837746/124758096-df7d3c80-df4b-11eb-8329-7deba3954617.jpg" width="400">

**Comment by pavi2410** [comment]
I will try to work on this feature. Can you please assign this issue to me?

**Comment by zhanghai** [comment]
I'm actually a bit undecided on this, because unlike AJShA, this app is an REPL which keeps history and supportings things like rotation. For example, how are you going to handle rotation and activity recreation without leaking the old activity held by the view?

**Comment by zhanghai** [comment]
You can always use the `activity` instance to create a helper function that helps you add a view somewhere, and you can save it into a script so that you may load it every time you start. However since there's no good way to support this natively without introducing bugs/leaks etc I'll close this for now.
